## Numpy operations on arrays and lists

In [1]:
#Vital numpy fuctions, datatypes, creating arrays (list of numbers) and viewing matrices (combination of multiple arrays)
#and arrays, sorting and manipulating arrays as well as applications
import numpy as np


In [2]:
# Numpy datatype (ndarray) and attributes

al = np.array([1,2,3])
al

array([1, 2, 3])

In [3]:
type(al)

numpy.ndarray

In [4]:
a2 = np.array([[3,4,5],
               [6,7,8]])

In [5]:
al.shape
a2.shape

(2, 3)

In [6]:
al.ndim, a2.ndim

(1, 2)

In [10]:

a2.size

6

In [11]:
al.size

3

In [12]:
type(al), type(a2)

(numpy.ndarray, numpy.ndarray)

In [13]:
#create a dataframe from numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  3  4  5
1  6  7  8

In [15]:
#create arrays of ones and zeros
ones = np.ones((2,3))
zeros = np.zeros((2,3))

In [16]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
range_array = np.arange(0, 10, 2)

In [20]:
range_array

array([0, 2, 4, 6, 8])

In [21]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[4, 7, 0, 9, 8],
       [6, 6, 2, 1, 6],
       [6, 9, 7, 7, 1]])

In [22]:
random_array.size

15

In [23]:
random_array.shape

(3, 5)

In [24]:
rand_array2 = np.random.random((3,5))
rand_array2

array([[0.61724016, 0.0253908 , 0.91828095, 0.07169531, 0.44031058],
       [0.02725397, 0.02617034, 0.63453707, 0.20265814, 0.27191132],
       [0.97773041, 0.84064277, 0.91129902, 0.28075896, 0.42229421]])

In [25]:
rand_array2.size

15

In [26]:
rand_array2.shape

(3, 5)

In [28]:
rand_array3 = np.random.rand(5, 3)

In [29]:
rand_array3

array([[0.7467935 , 0.63853148, 0.27207246],
       [0.81225289, 0.59324913, 0.90319556],
       [0.61279703, 0.297847  , 0.89193906],
       [0.72683899, 0.92903058, 0.61361342],
       [0.14010276, 0.48416078, 0.66521918]])

In [32]:
np.random.seed(seed=0)
random_array4 = np.random.randint(10, size=(5, 3))
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [34]:
random = np.random.random((5,3))

In [35]:
random = np.random.random((5,3))

In [36]:
random

array([[0.3595079 , 0.43703195, 0.6976312 ],
       [0.06022547, 0.66676672, 0.67063787],
       [0.21038256, 0.1289263 , 0.31542835],
       [0.36371077, 0.57019677, 0.43860151],
       [0.98837384, 0.10204481, 0.20887676]])

In [37]:
np.unique(random_array)

array([0, 1, 2, 4, 6, 7, 8, 9])

In [38]:
#Viewing arrays and matrices by indexing
a2[0]

array([3, 4, 5])

In [39]:
a3 = np.array([[[1,3,4], [4,5,6],[7,8,9]], [[10,11,12],[13,14,15],[16,17,18]]])

In [40]:
a3

array([[[ 1,  3,  4],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [41]:
a3.shape

(2, 3, 3)

In [42]:
a3.size

18

In [46]:
a3[0]

array([[1, 3, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
#Arithmetic functions in numpy
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

In [48]:
newarr

array([30, 32, 34, 36, 38, 40])

In [49]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)
newarr

array([-10,  -1,   8,  17,  26,  35])

In [50]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


In [51]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)
newarr

array([ 3.33333333,  4.        ,  3.        ,  5.        , 25.        ,
        1.81818182])

In [52]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [53]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [54]:
arr = np.arange(1, 10)

print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
